// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     value-schema.avsc
 */
package avroschema

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewComTopicInValueWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewComTopicInValue()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type ComTopicInValueReader struct {
	r io.Reader
	p *vm.Program
}

func NewComTopicInValueReader(r io.Reader) (*ComTopicInValueReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewComTopicInValue()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ComTopicInValueReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r ComTopicInValueReader) Read() (ComTopicInValue, error) {
	t := NewComTopicInValue()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
