// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     value-schema.avsc
 */
package avroschema

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// value schema for incoming topic ex) order
type Order struct {
	Name string `json:"Name"`

	FamilyName string `json:"FamilyName"`

	Birth int32 `json:"Birth"`

	CustomId string `json:"CustomId"`

	UnitPrice float64 `json:"UnitPrice"`

	Amount int32 `json:"Amount"`

	Credit float64 `json:"Credit"`

	Distance int32 `json:"Distance"`
}

const OrderAvroCRC64Fingerprint = "\x93߁\xcdj;NE"

func NewOrder() Order {
	r := Order{}
	r.UnitPrice = 0
	r.Amount = 0
	r.Credit = 0
	r.Distance = 0
	return r
}

func DeserializeOrder(r io.Reader) (Order, error) {
	t := NewOrder()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOrderFromSchema(r io.Reader, schema string) (Order, error) {
	t := NewOrder()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOrder(r Order, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Name, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FamilyName, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Birth, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CustomId, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.UnitPrice, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Amount, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.Credit, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Distance, w)
	if err != nil {
		return err
	}
	return err
}

func (r Order) Serialize(w io.Writer) error {
	return writeOrder(r, w)
}

func (r Order) Schema() string {
	return "{\"doc\":\"value schema for incoming topic ex) order\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"FamilyName\",\"type\":\"string\"},{\"name\":\"Birth\",\"type\":{\"logicalType\":\"date\",\"type\":\"int\"}},{\"name\":\"CustomId\",\"type\":\"string\"},{\"default\":0,\"name\":\"UnitPrice\",\"type\":\"double\"},{\"default\":0,\"name\":\"Amount\",\"type\":\"int\"},{\"default\":0,\"name\":\"Credit\",\"type\":\"double\"},{\"default\":0,\"name\":\"Distance\",\"type\":\"int\"}],\"name\":\"de.topic.in.Order\",\"type\":\"record\"}"
}

func (r Order) SchemaName() string {
	return "de.topic.in.Order"
}

func (_ Order) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Order) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Order) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Order) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Order) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Order) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Order) SetString(v string)   { panic("Unsupported operation") }
func (_ Order) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Order) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Name}

		return w

	case 1:
		w := types.String{Target: &r.FamilyName}

		return w

	case 2:
		w := types.Int{Target: &r.Birth}

		return w

	case 3:
		w := types.String{Target: &r.CustomId}

		return w

	case 4:
		w := types.Double{Target: &r.UnitPrice}

		return w

	case 5:
		w := types.Int{Target: &r.Amount}

		return w

	case 6:
		w := types.Double{Target: &r.Credit}

		return w

	case 7:
		w := types.Int{Target: &r.Distance}

		return w

	}
	panic("Unknown field index")
}

func (r *Order) SetDefault(i int) {
	switch i {
	case 4:
		r.UnitPrice = 0
		return
	case 5:
		r.Amount = 0
		return
	case 6:
		r.Credit = 0
		return
	case 7:
		r.Distance = 0
		return
	}
	panic("Unknown field index")
}

func (r *Order) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Order) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Order) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Order) HintSize(int)                     { panic("Unsupported operation") }
func (_ Order) Finalize()                        {}

func (_ Order) AvroCRC64Fingerprint() []byte {
	return []byte(OrderAvroCRC64Fingerprint)
}

func (r Order) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Name"], err = json.Marshal(r.Name)
	if err != nil {
		return nil, err
	}
	output["FamilyName"], err = json.Marshal(r.FamilyName)
	if err != nil {
		return nil, err
	}
	output["Birth"], err = json.Marshal(r.Birth)
	if err != nil {
		return nil, err
	}
	output["CustomId"], err = json.Marshal(r.CustomId)
	if err != nil {
		return nil, err
	}
	output["UnitPrice"], err = json.Marshal(r.UnitPrice)
	if err != nil {
		return nil, err
	}
	output["Amount"], err = json.Marshal(r.Amount)
	if err != nil {
		return nil, err
	}
	output["Credit"], err = json.Marshal(r.Credit)
	if err != nil {
		return nil, err
	}
	output["Distance"], err = json.Marshal(r.Distance)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Order) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Name"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Name); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Name")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FamilyName"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FamilyName); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FamilyName")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Birth"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Birth); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Birth")
	}
	val = func() json.RawMessage {
		if v, ok := fields["CustomId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CustomId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for CustomId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["UnitPrice"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.UnitPrice); err != nil {
			return err
		}
	} else {
		r.UnitPrice = 0
	}
	val = func() json.RawMessage {
		if v, ok := fields["Amount"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Amount); err != nil {
			return err
		}
	} else {
		r.Amount = 0
	}
	val = func() json.RawMessage {
		if v, ok := fields["Credit"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Credit); err != nil {
			return err
		}
	} else {
		r.Credit = 0
	}
	val = func() json.RawMessage {
		if v, ok := fields["Distance"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Distance); err != nil {
			return err
		}
	} else {
		r.Distance = 0
	}
	return nil
}
